create table "public"."entry_tags" (
    "journal_entry_id" uuid not null default gen_random_uuid(),
    "tag_id" uuid not null default gen_random_uuid()
);


alter table "public"."entry_tags" enable row level security;

create table "public"."journal_entries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "tags" text[],
    "content" text,
    "updated_at" date default now()
);


alter table "public"."journal_entries" enable row level security;

create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."tags" enable row level security;

CREATE UNIQUE INDEX entry_tags_pkey ON public.entry_tags USING btree (journal_entry_id, tag_id);

CREATE UNIQUE INDEX journal_entries_pkey ON public.journal_entries USING btree (id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."entry_tags" add constraint "entry_tags_pkey" PRIMARY KEY using index "entry_tags_pkey";

alter table "public"."journal_entries" add constraint "journal_entries_pkey" PRIMARY KEY using index "journal_entries_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."entry_tags" to "anon";

grant insert on table "public"."entry_tags" to "anon";

grant references on table "public"."entry_tags" to "anon";

grant select on table "public"."entry_tags" to "anon";

grant trigger on table "public"."entry_tags" to "anon";

grant truncate on table "public"."entry_tags" to "anon";

grant update on table "public"."entry_tags" to "anon";

grant delete on table "public"."entry_tags" to "authenticated";

grant insert on table "public"."entry_tags" to "authenticated";

grant references on table "public"."entry_tags" to "authenticated";

grant select on table "public"."entry_tags" to "authenticated";

grant trigger on table "public"."entry_tags" to "authenticated";

grant truncate on table "public"."entry_tags" to "authenticated";

grant update on table "public"."entry_tags" to "authenticated";

grant delete on table "public"."entry_tags" to "service_role";

grant insert on table "public"."entry_tags" to "service_role";

grant references on table "public"."entry_tags" to "service_role";

grant select on table "public"."entry_tags" to "service_role";

grant trigger on table "public"."entry_tags" to "service_role";

grant truncate on table "public"."entry_tags" to "service_role";

grant update on table "public"."entry_tags" to "service_role";

grant delete on table "public"."journal_entries" to "anon";

grant insert on table "public"."journal_entries" to "anon";

grant references on table "public"."journal_entries" to "anon";

grant select on table "public"."journal_entries" to "anon";

grant trigger on table "public"."journal_entries" to "anon";

grant truncate on table "public"."journal_entries" to "anon";

grant update on table "public"."journal_entries" to "anon";

grant delete on table "public"."journal_entries" to "authenticated";

grant insert on table "public"."journal_entries" to "authenticated";

grant references on table "public"."journal_entries" to "authenticated";

grant select on table "public"."journal_entries" to "authenticated";

grant trigger on table "public"."journal_entries" to "authenticated";

grant truncate on table "public"."journal_entries" to "authenticated";

grant update on table "public"."journal_entries" to "authenticated";

grant delete on table "public"."journal_entries" to "service_role";

grant insert on table "public"."journal_entries" to "service_role";

grant references on table "public"."journal_entries" to "service_role";

grant select on table "public"."journal_entries" to "service_role";

grant trigger on table "public"."journal_entries" to "service_role";

grant truncate on table "public"."journal_entries" to "service_role";

grant update on table "public"."journal_entries" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";


